# -*- coding: utf-8 -*-

from ..custom_exception import CustomException


class EthdoError(CustomException):
    """Exception raised for errors in the ethdo call functions."""
